### ISSUE TITLE
Jedlo NodeSchool Bratislava #1 12.12.2015

### ISSUE THREAD

**Issue by yangwao** [nodeschool/bratislava#10]
Jedlo budem objednávať, ale kto chce môže sa ísť najesť v okolí.
Postup je, že si pozriete na čo máte chuť vo vybraných reštauráciach a napíšete do komentára `meno_reštaurácie.jedlo`, napr
`BEMBA.Špagety s bazalkovým pestom 300g`

Ak bude niekde menej ako tri objednávky, nebude sa objednávať, napíšem Vám, nebojte sa.
### RAW

http://www.ham.sk/restauracia/bemba
### PIZZA+

http://www.ham.sk/restauracia/stromovka
### INDIA (od 12h)

http://www.ham.sk/restauracia/royal-kashmir
### SALAD/FALAFEL/HUMMUS (od 12h)

http://www.ham.sk/restauracia/frischco
## Alternatívne stravovanie

v dosahu 3 minút pešo
Kontakt https://www.zomato.com/bratislava/kontakt-star%C3%A9-mesto-bratislava-i/menu
Green Budha https://www.zomato.com/bratislava/green-buddha-star%C3%A9-mesto-bratislava-i
Minerva https://www.zomato.com/bratislava/minerva-star%C3%A9-mesto-bratislava-i

Keby ste niečomu nerozumeli, otázky na gitter https://gitter.im/nodeschool/bratislava

Dobrú chuť!

**Comment by marty-buly** [comment]
STROMOVKA.Salami pizza
dik

**Comment by jlabaj** [comment]
royal-kashmir.Chicken Masala + Tandoori placka

**Comment by Cyril212** [comment]
STROMOVKA. Funghi 400g

**Comment by mako1131** [comment]
BEMBA.Zeleninove šatôčky 300g

**Comment by alekseypotapov-dev** [comment]
STROMOVKA, Lasagne Bolognese 300g

**Comment by kubadlo** [comment]
STROMOVKA.Vegetariana 400g

**Comment by Ivkaa** [comment]
BEMBA.Zeleninové šatôčky 300g

**Comment by oreqizer** [comment]
BEMBA. Spagetti s pestom 2x

**Comment by Axxxela** [comment]
BEMBA.Quacamole s pizza prstami 300g

**Comment by erichstark** [comment]
STROMOVKA. Lasagne Bolognese 300g
ak bude mozne tak aj
STROMOVKA. Hovadzi || Kuraci vyvar 0,3l

**Comment by robooo** [comment]
STROMOVKA.Šalát Kurací 300g

**Comment by SamuelPecar** [comment]
STROMOVKA. Kuracie prsia na grile

**Comment by ghost** [comment]
STROMOVKA.Prosciutto 1,7 400g

**Comment by aspintm** [comment]
STROMOVKA. Pizza Hawai

**Comment by madox2** [comment]
STROMOVKA. Salami 1,7 400g

**Comment by jangondol** [comment]
ROYAL_KASHMIR.Hydarbadi Korma 150g

**Comment by roberto68** [comment]
ROYAL_KASHMIR.Hydarbadi Korma 150g

**Comment by tomas-radic** [comment]
STROMOVKA.Prosciutto

**Comment by PotvoraN** [comment]
Frischco. Falafel so zeleninou + polievka 230g + 2dcl

**Comment by ghost** [comment]
frischco Falafel v pite 230g

**Comment by asinex** [comment]
STROMOVKA.Vegetariana 400g

**Comment by yangwao** [comment]
BEMBA.Quacamole s pizza prstami 300g

**Comment by maht0rz** [comment]
STROMOVKA. lasagne 
+
STROMOVKA. lasagne

**Comment by robert1c** [comment]
STROMOVKA. Pizza Hawai

**Comment by zuzana** [comment]
STROMOVKA:  Pizza Hawai. Vdaka.

**Comment by ghost** [comment]
STROMOVKA // Quattro stagioni  450g

**Comment by ins0mn1a** [comment]
Pizza+ / Spaghetti Bolognese 1,9,7 300g

**Comment by suezjk** [comment]
PIZZA+ / Spaghetti Bolognese 1,9,7 300g

**Comment by apansky** [comment]
STROMOVKA.Salami pizza

**Comment by mr-memetic** [comment]
PIZZA+(stromovka) Salami pizza

**Comment by PotvoraN** [comment]
Veronika_frischo. hummus so zeleninou + polievkou 230g +2dcl

**Comment by 16961714b** [comment]
STROMOVKA.Vegetariana 400g

**Comment by asinex** [comment]
STROMOVKA.Vegetariana 400g

**Comment by Sb8691** [comment]
STROMOVKA.Salami pizza
dik

**Comment by marcelmokos** [comment]
STROMOVKA.Prosciutto pizza

**Comment by asinex** [comment]
SOM STRASNE HLADNY 
:D

**Comment by jangondol** [comment]
OK, UPDATE (keďže ROYAL_KASHMIR má status 503): STROMOVKA.Lasagne Bolognese 300g

**Comment by roberto68** [comment]
MINERVA, cheese burger

**Comment by yangwao** [comment]
objednane, objednavky z frisch.co budu, royal kashmir vyfailoval.
Nieco kratko po 13 pride food, vdaka za trpezlivost, vydosovali sme Stromovku :)

**Comment by yangwao** [comment]
Zatial costs za jedlo+pitie, 157,32€+38,30€+12,43€+34x2€ = 276,05€

### Do ďalšieho meetupu by sa hodili sponzori, ak by vedel niekto ďalší pomôcť :)
