### ISSUE TITLE
Feedback na NodeSchool #1

### ISSUE THREAD

**Issue by yangwao** [nodeschool/bratislava#11]
Ahoj, pár ľudí dávalo useful feedback čo sa dá vylepšiť na ďalšom evente a tu by som rád pozbieral od ostatných. Jeden problém môže mať viac ako jedno riešenie.

> Za mna bolo, ze som nedodrzal casovy deadline s jedlom a neobjednaval uz o 11:00, (ale az o 11:40-12:20). 
> 
> Nabuduce bude deadline este pred polnocou a mozu sa tak prevadzky lepsie pripravit a vsetci budu spokojni :)

V podobnej forme by som prosil sa kludne rozpisat, co bol pre Vas problem, ci uz porozumenie, zle vysvetlenie, uvod, co si pripravit. Do druheho riadku napiste ako by ste to riesili.

Vdaka!
Matej

**Comment by jlabaj** [comment]
Dal by sa zopakovat docker na buducom nodeschool? Niektori museli odist skorej a nestihli to :)

**Comment by roberto68** [comment]
mozno rozdelenie na pokrocilych  (co chcu robit nejake konkretne veci svoje/ co ty navhrnes) a  zaciatocnikov - lebo bolo tam dost ludi co sa nie ze oboznamovali s node.js itself ale s cmd-line (aelbo mozno aj 3 skupiny) A este nejake dobre learning resources, sample apps tutorials... lebo mne tie nodeshcool tutorialy pridu trochu confusing (zadanie) a vytrhnute s kontextu, ja osobne si na real life apkach viem lepsie predstavit vo co go  (myslim  tutorial s popisom...) kedze samotny JS ovladam docela slusne. A este par rad o frameworkoch a dobrych developement tools...

**Comment by SOULPWRD** [comment]
Myslienku nodeschool absolutne kvitujem. Vyborny napad, prijemne prostredie a pohodova pracovna atmosfera. 2 veci, co by som "vytkol". Berte to, prosim, ako skutocne konstruktivnu kritiku, ziadny trapny hejt alebo moralizovanie.
1. rozdelenie do skupin, pokrocilejsi a menej prokrocili (pripadne zaciatocnici). Rozumiem zaroven, ze tam nie je vela miesta a prihlasilo sa viacej ludi, nez sa realne ocakavalo.
2. Zjavne trpim akademickou deformaciou, ale to preto, lebo akademicke prostredie mam rad (aj napriek tomu, v akom je momentalnom stave a ake vie byt mimoriadne nudne a neatraktivne). Jedno vsak, co som uprimne nevedel predychat boli prezentacie.
   A teraz preco. Na uvod - osadenstvo. Realne tam bolo vela zaciatocnikov (vratane mna), ktory mali skusenost s nodejs mensiu ako 2(3?)/5. Pouzijem priklad prezentacie o Dockeri. Mate povedzme 15 - 20 (30?) min na prezentaciu, kde mate predstavit, co je to Docker - teda ako funguje, preco je to fasa vec a podobne. Tychto 20 minut ste v konecnom dosledku venovali pokrocilej praci s Dockrom a vasim problemom, ktore riesite v praci + ten neatraktivny IT zargon. Chalani nehnevajte sa, ale nemali by ste si dovolit pouzivat IT zargon na takejto akcii a predovsetkym s takymto poctom zaciatocnikov.
   Predstavte si, ze neviete nic z programovania a niekto vam zacne slovensko-anglickou hatlaninou hovorit, len tak z fleku, o OOP alebo pokrocilych funkciach a nastrojoch v programovani. V tom momente ste nahrati, proste nic, ani obraz ani zvuk. Po pol hodine to zbalite a nebudete mat chciet docinenia s programovanim na veky vekov (aj kebyze mate na to velky potencial).
   Jednoducho, dobry prezentujuci (ucitel, alebo ktokolvek iny), je taky, ktory vie podat akukolvek odbornu alebo inak specificku vec ludskym jazykom a pritom zachyti podstatu veci tak, ze to pochopi aj clovek, ktory o tom nikdy predtym nepocul. To si vsak vyzaduje trening, v tom je umenie a krasa prezentovania.

Este raz, v prvom rade, ako som uz Matejovi na FB pisal, bol som skutocne poteseny touto akciou. Tesim sa na dalsie kolo. :+1: (samozrejme, ak sa po tomto prispevku nenajdem na ban liste Nodeschoolu :) )

**Comment by vlapo** [comment]
Podobne davam do placu moj nazor:
1. Prezentacie - chapem, bolo to dost na rychlo zohnat niekoho kto bude prezentovat, no dalsie stretnutia by mali podla mna obsahovat viac speekerov. Touto cestou by som rad pochvalil prezentaciu @srigi (multithreading v Nodejs). Myslim, ze som v nej nasiel co som ocakaval od nodeschool vol. 1 (intro, troska omacky, prakticky priklad, diskusia). Co sa tyka dockeru nemozem sudit, pretoze posun prezentacie o X hodin (!!!) je podla mna nezodpovednost.
2. Komunikacia
   - po uvodnej reci boli vsetci okolo dost zmateny co sa vlastne ma robit a v akom vesmire sa to vobec ocitli. Preto by bolo fajn mat repraky (aj vzadu v miestnosti) a povedat troska viac o akcii, hlavne ked bolo tolko zaciatocnikov.
   - gitter - fajn miesto kde sa dalo napisat ked mal niekto problem a potreboval pomoct s nodejs. Avsak pri informaciach ako: kedy pride jedlo, je problem s objednavkou, prezentacie budu meskat alebo nebodaj "hori" utekajte by bolo fajn sa postavit prejst miestnost a povedat to ludom face to face - podla mna o tom tieto stretnutia aj maju byt (komunikovat medzi sebou nie len chatom, emailom)
3. Nieco menej dolezite - studena pizza - naozaj si vazim sponzorskeho jedla a aj ochoty vsetko objednat naraz a nezatazovat nas nutnostou mysliet na to co budeme jest. Ale ked vam po par hodinach cakania s prazdnym zaludkom pride pizza, ktoru by som inak donaske asi vratil, je to dost podpasovka. Som rad, ze sa @yangwao poucil. Koordinovat 50 hladnych zaludkov je challenge :)
   _Note: Ak za to zdrzanie a studenu pizzu moze stromovka tak som si odtial asi objednal naposledy :)_

Moja troska do dalsieho stretnutia:
1. Skupiny - tu sa viac menej stotoznujem s napadmi @roberto68 a @SOULPWRD. Rozdelenie do skupin mi pride ako velmi dobry napad, Mozno akysi "harmonogram". 
   - od 9:00 - 13:00 zaciatocnici dajme tomu s rychlim intro co je nodejs, javascript, konzola - verim tomu ze by sa naslo vela z pokrocilejsich nodejs dev, ktory na stretnuti boli a vedeli by taketo intro poskytnut (vyskillovat sa tym aj v prezentovani) + pomoct pri individualnej praci jednotlivych zaciatocnikov
   - 13:00 obed, coffee/tea/cocoa
   - 14:00 mozu zacat prichadzat ludia, ktory sa zaujimaju o pokrocilejsiu formu stretnutia, prednasky s komplexnejsou tematikou, pripadne vyhradit jednu miestnost pre zaciatocnikov, ktory chcu dalej pokracovat v cviceniach s dakymi mentormi.
2. prednasky - kvalitne a zaujimave prednasky v dostatocnom pocte a podla harmonogramu. Existuje vela kvalitnych packages, ktore by sa dali priblizit. Mozno vypisat dake okruhy a snad sa najdu ludia co budu chciet troska potrapit svoje prezentacne a developerske zrucnosti.
3. harmonogram - meskanie dockeru ma proste dostalo a nebol som urcite sam. Ked je nieco naplanovane malo by to +/- hodina sediet. To iste zaciatok.
4. Guru/Mentor - chybali mi tam ludia s velkym cervenym napisom "Pytajte sa. Rad vam pomozem." hlavne pre zaciatocnikov. Cize viac pokrocilejsich ludi ochotnych pomoct druhym.
5. Lead guru - clovek, ktory ked nieco povie vsetci ho pocuvaju lebo rozprava organizacne veci, uvadza speekerov, oznamuje zmeny, drzi zvoncek oznamujuci obed.
6. Osobne by som mozno prednaskovu cast presunul niekde do blizkeho podniku, kde by sa dalo diskutovat pri pivku a napr zaciatocnikov, ktorych pokrocilejsie prednasky nezaujimaju nechat pracovat s mentormi v priestoroch progressbaru.

Rad by som podakoval ludom s progressbaru (hlavne @yangwao, ktory bol najviac viditelny) za tolku snahu v tak kratkom case. Dufam, ze pocet ludi, ktory prisiel vas riadne nakopol a dalsie stretnutie bude kvalitnejsie a lepsie. Osobne som vsak od toho cakal troska viac, co je vsak len moj subjektivny nazor :) Som zvedavy na dalsie stretnutie :)

**Comment by roberto68** [comment]
btw. mohol by si nieco spravit s tym mojim pull requestom :dancers:

**Comment by yangwao** [comment]
@jlabaj mohol by som v nejakej krátkosti, alebo rovno píš otázky na gitter, prednáška bola naplánovana len pár hodín, čiže zázrak bol, že bola, možno @newPOPE bude chciet približiť ešte raz nejake praktické demo.

@roberto68 rozdelit to na skupiny som chcel od zaciatku, ale mam moralny a eticky problem, podla coho ludi rozdelit? Pre mna je to n-novych ludi, neviem odhadnut kto co vie, preto som to nechal na seba hodnoteni. To ze sa ludia nepozoznamovali bola asi viac moja chyba, na tom chcem popracovat, poparovat zaciatocnika so zaciatocnikom a pojde to rychlejsie, ucel stretnutia nodeschoolu, pair-learning :)
Hej problem som vnimal, ze ludia si to pomylili s how-to-pc. Asi venujem extra cas ludom, aby si rozbehali zakladny enviroment, nech ich nic neblokuje, lebo to zozralo vela casu niektory si myslim aj co som postrehol.
@roberto68 Vedel by si pripravit na nieco example/demo?

@SOULPWRD podla coho ludi identifikujes kto patri kam? :)
IT zargon beriem, je to o pouziti spravnej terminologii, moze sa to zlepsit. Adam sa pytal ci ma niekto nejake otazky, vsetci mlcali ak si pamatam :)
Hm ak som pochopil tvojej myslienke, narazas na format akym sa to odovzadavalo zaciatocnikom, nad niecim sa moze popremyslat, ale nie som pedagog, ale ak vies pomoct, kludne sa rozpis tu alebo na gitter.
Vedel by si si pripravit prezentaciu napr k veciam, ktore si sa naucil? Kedze ja mam iny level, mozno by si to vedel lepsie priblizit ludom ty?

@vlapo posun prezentacie moze byt aj moja chyba, ale @newPOPE prisiel ltt z BB, cize som rad aj za jeho prispevok, ale oneskoreny. Ludia dobrovolne prispievaju svojim casom pre inych, mozem si nabuduce nechat zalezat na timekeepingu, pripadne by si mohol robit timekeeping? Mne cas leti rozne aj ked ho viem pocitat, sledovat timetable akonahle zacnes riesit nejaky problem s niekym neustriehnes :) (napr objednavanie jedla)
ad **intro**, priznavam totalne zlyhanie, nemal som to nacvicene, nemal som v Progressbare 60+ ludi, mohol si si vsimnut, ze sme riesili ako usadit ludi, dat im invidualne intro k inym veciam. Na dalsie sa pokusim 
@vlapo vies prispiet nejakou prednaskou?
Oznacenie ludi som menoval par, ale to sa lahko zabudne, to sa vylepsi :)
@vlapo kam by si presunul prednaskovu cast? Ludia v podniku sa uplne rozptylia. Ak nas bude viac, som za, ale v takomto malom pocte, je lepsie ked pokrocili zostanu s newcomers a vedia si pomoct :)
@vlapo co viac si cakal? Ja som cakal viac sponzorov :)

Moj list co si odnasam zatial z feedbacku
- lepsie intro pre ludi - uvodnu aspon par minutovu rec, preco prisli, co sa dozvedia a co si odnesu
- rozdelenie newcomers && pokrocili 
- timekeeping
  * zlepsit general comm
- jedlo - uzatvarat objednavky 3 hodiny pred objednavkou (vydosovali sme ham.sk, pizerku a dalsie prevadzky)
- oznacenie orgov / pokrocilejsich

**Comment by srigi** [comment]
Pridaj aj ja svoj nazor. Bude to trocha kriticke, dufam, ze to nebude prilis vadit. Mam iba dva body:
1. priestor je IMHO totalne nevhodny pre "vzdelavanie". Kovbojske sedenie vseliako po gaucoch, kreslach, dve miestnosti. Progressbar je podla mojho nazoru fakt nevhodny na takuto akciu.
2. forma eventu mi prisla dost nepremyslena - ucit ludi Node tak ako som to videl pokladam za stratu casu. Vypracovat si nejake konzolove lekcie moze kazdy doma sam. Podla mna by forma mala viac pripominat skolu - lektor a ziaci. Ukazka kodu na projektore, vysvetlenie, cvicenie.

**Comment by yangwao** [comment]
@srigi ano, priestor moze byt nevhodny, vies vybavit lepsi zadarmo? Som otvoreny ponukam cestovat

@srigi ktore lekcie sa clovek nenauci doma sam? Podujmes sa na nejake vysvetlit? :)

Nodeschool meetupy sú sociálny layer, kde sa ľudia popáruju a učia sa dvaja začiatočníci spolu napr., neviem aku úlohu tu má učiteľ, ktorý nemá pedagogické minimum a (ne)riešil by čo asi tak ukázať. Príde mi, že to formuluješ dosť z pohľadu boha :)

ps. necital si uvod, ked som pisal, ze spis problem a ponukni riesenie, riesenie si nenapisal :)

**Comment by newPOPE** [comment]
So zopakovanim Dockeru nie je problem. Uvedomujem si (za co sa aj ospravedlnujem), ze mi trochu uslo publikum (zaciatocnici) a "hantyrka" ktoru som pouzival bola advanced. Ak bude zaujem tak sa na to viem pripravit aj s nejakymi slide-ami a ukazkami (nakolko to bolo take punkove) ako to pustat (node v nejakej verzii pripadne ako si nastavit vlastny stroj pre projekt)

**Comment by yangwao** [comment]
@newPOPE super, dávam ťa do programu?

**Comment by newPOPE** [comment]
@yangwao mozes

**Comment by yangwao** [comment]
ešte teraz ma napadlo (vdaka Lulu Pov), že zjednoduším celý proces prihlasovania cez typeform. 
By som mal davat ludom otazky 
- ci pridu / chceli by prist; 
- odkial k nam ide BA / mimo BA;
- github handle
- twitter handle
- úroveň znalosti JS, if high could be a mentor?
- platformu notebooku win/osx/linux,
- co chcu jest na vyber z tych pizz 
- aku kavu budu chciet, that's it ?

**Comment by yangwao** [comment]
typeform bol vytvoreny :) https://yangwao.typeform.com/to/Qb8qdR

**Comment by vlapo** [comment]
@yangwao 
- ako timekeeper by stacil mozno budik na mobile :)
- prednaska - ak bude niekedy priestor vo volnom case mozno sa na niecom podujmem. Na dalsom nodeschool by som ale rad pomohol ako pokrocili pre zaciatocnikov.
  - mne osobne sa pacili napr JavaGroup v Nervose a posedenicko pri pivku a dobrej prednaske. ale to je mozno uz mimo nodeschool, skor dake NodeGroup stretka.
  - cakal som viac prednasok

**Comment by yangwao** [comment]
Ad viac prednasok - toto nema byt meetup s prezentaciami, prezentacie su highly optional :)
