### ISSUE TITLE
Food NodeSchool Bratislava #1 23.1.2016

### ISSUE THREAD

**Issue by yangwao** [nodeschool/bratislava#12]
Jedlo sa pre tentokrát bude objednávať aspoň 3h dopredu, aby nebolo studené v hodine 12tej. :)

Postup zostáva, pozriete na čo máte chuť vo pizzerii a napíšete do komentára názov pizze, prípadne ak máte niečo extra, kľudne. Tento meetup obmedzím objednávky len na pizzu, kto bude chcieť ísť inde, dáte vedieť na gitter/spýtate sa, v okolí je mnoho možností :)

Sponzor ešte nie je istý, čiže rátajte, že zaplatíte buď na mieste cash, bitcoiny alebo transfer :)
### PIZZA

http://www.ham.sk/restauracia/stromovka
## Alternatívne stravovanie

v dosahu 3 minút pešo
Kontakt https://www.zomato.com/bratislava/kontakt-star%C3%A9-mesto-bratislava-i/menu
Green Budha https://www.zomato.com/bratislava/green-buddha-star%C3%A9-mesto-bratislava-i
Minerva https://www.zomato.com/bratislava/minerva-star%C3%A9-mesto-bratislava-i

Keby ste niečomu nerozumeli, otázky na gitter https://gitter.im/nodeschool/bratislava

Dobrú chuť!

**Comment by maht0rz** [comment]
Salami pizza

**Comment by haness** [comment]
Vegetariana o/

**Comment by kat-kardaschian** [comment]
Margherita :-)

**Comment by mariusrak** [comment]
Salami

**Comment by kat-kardaschian** [comment]
ale ja by som zjedla tuším aj dve :-D

**Comment by yangwao** [comment]
Jedlo zaregistrujete cez tento typeform https://yangwao.typeform.com/to/Qb8qdR
duplikáty vytriedim potom, tí čo ste uz zapísali aj na typeform :)

**Comment by kat-kardaschian** [comment]
toto dúfam platí, ja som mala margheritu
