### ISSUE TITLE
Coffe NodeSchool Bratislava #2 23.1.2016

### ISSUE THREAD

**Issue by yangwao** [nodeschool/bratislava#13]
# Group Order kávy z [Urban Bistra](http://urbanbistro.sk/)
### napíš do komentára akú kávu by si chcel/a
- espresso
- americano
- flat white
- cappuccino
- latte
- espresso flight
- filter coffe
- filter coffe for two
- cold brew
- iced latte
- espresso tonic
- hot chocolate

Po objednávky pôjde @maht0rz, ak bude viac káv, určite bude potrebovať pomoc :)
[Kavové menu](http://urbanbistro.sk/functions/resize.php?o=../i/ubm1.jpg&w=650&h=850)
Ceny sú približne {2;2,5;3}€, ked dáte 3€, potom si vydáte :)

Majú tam aj [various snacks](http://urbanbistro.sk/functions/resize.php?o=../i/ubm5.jpg&w=650&h=850) keď tak

**Comment by kat-kardaschian** [comment]
flat white a latte a kludne pomôžem odniesť

**Comment by yangwao** [comment]
Coffe zaregistrujete cez tento typeform https://yangwao.typeform.com/to/Qb8qdR
duplikáty vytriedim potom, tí čo ste už zapísali aj na typeform :)
