### ISSUE TITLE
Lunch coffe 23.1.2016

### ISSUE THREAD

**Issue by yangwao** [nodeschool/bratislava#15]
Máme ďalšieho sponzora na kávu [Pygmalios.com](http://www.pygmalios.com)
Vyber si kavu z [urbanbistro.sk/](http://urbanbistro.sk/) a napis ju do komentaru, najlepsie needituj uz potom. Deadline na objednavku do 11:50

**Comment by yangwao** [comment]
hot chocolate

**Comment by yangwao** [comment]
preberam z gitteru po 11:40, 3x espreso, 3x americano, 3x mocha, hot choclate, caffe au lait,

**Comment by marty-buly** [comment]
1x americano pls ;)

**Comment by Benjji** [comment]
1x caffe mocha + 1x caffe au lait please

**Comment by zixo** [comment]
1x americano prosim

**Comment by kat-kardaschian** [comment]
latte ďakujem

**Comment by robooo** [comment]
1x espresso dik
