### ISSUE TITLE
Stickermule order

### ISSUE THREAD

**Issue by yangwao** [nodeschool/bratislava#16]
Ahoj, kto by chcel zo stickermule nalepky, tak budem objednavat koncom mesiaca, kto by chcel tak nech da link alebo collection, na gitteri sa dohodneme potom.
**Deadline, end of January 2016.**

Napr za mna https://www.stickermule.com/marketplace/1895-stormtrooper

**Comment by yangwao** [comment]
Objednal som sticker sample zo stickermule, uvidím.
Este som dostal odporucenie na https://www.diginate.com/products/vinyl-sticker/ od chalanov z [sushijs.org](http://www.sushijs.org/), ale nevidim tam sample order

**Comment by robooo** [comment]
ja poprosim https://www.stickermule.com/marketplace/3378-write-code-drink-coffee ;)

**Comment by yangwao** [comment]
https://www.stickermule.com/marketplace/1910-go-lang

**Comment by martinfridrich** [comment]
https://www.stickermule.com/marketplace/4358-bears-will-kill-you
https://www.stickermule.com/marketplace/9514-pixel-shell-clear

**Comment by yangwao** [comment]
https://www.stickermule.com/marketplace/10200-webtorrent
https://www.stickermule.com/marketplace/10199-javascript-standard-style
http://hexb.in/meta/jsgirls.json
http://hexb.in/meta/icelandjs.json
https://www.stickermule.com/marketplace/3442-there-is-no-cloud
https://www.stickermule.com/marketplace/3745-respect-the-zone-clear
https://www.stickermule.com/marketplace/3704-laser-cats-poser-child

Este by som chcel offline sticker, nasiel som len toto, ale cez stickermule custom by som ked tak dal spravit 
http://www.redbubble.com/people/stephaniehertl/works/12825586-slow-internet?grid_pos=7&p=sticker
http://www.redbubble.com/shop/offline

**Comment by yangwao** [comment]
Offline-first hex sticker s T-rex runnerom bude soon, ked by niekto chcel :)

**Comment by yangwao** [comment]
Odpoved zo Stickermule, kedze by som chcel si dat spravit este t-rexa a icelandjs. 

> Once we review your application, we’ll send you information on next steps. We aim to respond to everyone within 30 days.

Chcete nalepky hned alebo mozem pockat a objednat ich neskor?

Este som nasiel iny shop https://hexi.pics/ a nalepky tam vyzeraju lacnejsie tak zvazim ale netusim aka je kvalita :)

**Comment by yangwao** [comment]
Offline T-Rex je up https://github.com/maxogden/hexbin/pull/81 :)

**Comment by yangwao** [comment]
a z hexi by som chcel zobrat tieto https://hexi.pics/items/91851923ee35303d49bc531bf52bdd87
https://hexi.pics/items/c582b560f4c9783f46b2f90ec32ad24b
https://hexi.pics/items/4125f4db99d525909d5b7d8bf657e8fd
https://hexi.pics/items/19693160d24746e42df710523e704a61
len su tiez celkom drahe.

**Comment by yangwao** [comment]
https://www.stickermule.com/marketplace/7115-staying-sharp-with-angular-dot-js (olso)

**Comment by yangwao** [comment]
Ivka 3ks https://www.stickermule.com/marketplace/4379-i-speak-fluent-sarcasm
Tento vikend to uz asi objednam a uzavriem, zaciatkom marca najneskor by mali prist tipujem :)

**Comment by ShockiTV** [comment]
http://www.stickermule.com/marketplace/5515-reactjs
http://www.stickermule.com/marketplace/1026-docker-stickers
http://www.stickermule.com/marketplace/2235-node-dot-js

**Comment by yangwao** [comment]
> Currently expected to arrive by Friday, March 11 2016

zobral som este 5 ks nodeschool international sticker!  :rocket:

**Comment by yangwao** [comment]
https://www.facebook.com/photo.php?fbid=1127918867252302&set=a.923235021054022.1073741830.100001025986242&type=3&theater&notif_t=like
https://www.instagram.com/p/BCsS9oUsDhd/?taken-by=yangwao

@ShockiTV tebe mozem nechat v Progressbare
@robooo tebe ju necham kde?

este som to nerozravatal ale poslem instrukcie asi sem )

**Comment by yangwao** [comment]
@robooo ~5.5€
@martinfridrich ~7.4€
@ShockiTV ~11.7€
ivka ~7.3€

SK7411000000002616301505 staci nejak popis stickermule :)
