### ISSUE TITLE
NodeSchool Bratislava #3 meetup 27.2.2016

### ISSUE THREAD

**Issue by yangwao** [nodeschool/bratislava#18]
Ahoj, tretie kolo, **27.2.2016 v Progressbare** organizujem all-day NodeSchool meetup (~ **9am-4:30pm**)

**Ak viete o ľudoch, ktorí by sa chceli naučiť programovať, pozvite ich.**

If you are non-slovak speaking attendee, let me know, we speak english as well!

**RSVP**
# [Zaregistruj sa cez tento formulár](https://yangwao.typeform.com/to/wdZuNE)
###### Social
- [Daj Going a pozvi dalších https://www.facebook.com/events/178025195897152/](https://www.facebook.com/events/178025195897152/)

[![Join the chat at https://gitter.im/nodeschool/bratislava](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/nodeschool/bratislava?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)
#### Sponzori sú
- [Aktiv.io](https://www.aktiv.io)
- [Progressbar](https://www.progressbar.sk)

Pozvite aj dievčatá, máme [code of conduct](https://github.com/nodeschool/bratislava/blob/master/codeofconduct.md) a budeme ho dodržiavať
### S čím aktuálne potrebujem pomôcť?
- promo samotného eventu, pozvite známych, kľudne napíšte kam to viete fwdnúť alebo kde to mám postnúť
- handsome co-organizátora
- hľadám šikovných mentorov ochotou pomáhať pri basics javascript & node.js :)
- pritiahnuť viac dievčat/žien, aby sme držali gender balance
- peknú stránku nodeschool/bratislava
## Novinky oproti predchádzajúcemu meetupu
- budú skupiny pre **javascripting**
- skupina, ktorá bude využívať znalosti z predchádzajúcich kurzov

**Ak chcete prísť [zaregistrujte sa cez tento formulár](https://yangwao.typeform.com/to/wdZuNE)**

Matej

**Comment by MiroJanosik** [comment]
FB event hovori 9:00 - 16:30, github hovori 10-17:00, tak odkedy sa otvaraju dvere?

**Comment by yangwao** [comment]
@MiroJanosik ju, vdaka, menil som to len z mobilu, tu som zabudol, opravene
