### ISSUE TITLE
Nodeschool Bratislava meetup 12.12.2015

### ISSUE THREAD

**Issue by yangwao** [nodeschool/bratislava#2]
Ahoj, po prieskume na FB som sa rozhodol, že **12.12. v Progressbare zorganizujem all-day** Nodeschool meetup. (~ 10am-7pm)

**RVSP**
- [https://www.facebook.com/events/145916095770052/](https://www.facebook.com/events/145916095770052/)
- [http://www.meetup.com/nodeba/events/227107676/](http://www.meetup.com/nodeba/events/227107676/)

[![Join the chat at https://gitter.im/nodeschool/bratislava](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/nodeschool/bratislava?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)

If you are non-slovak speaking attendee, let me know, we speak english as well!
#### AIM meetupu je pre

**new-comers** sa naučiť JS a Node.js základy
**advanced** ľudí naučiť hands-on 
- streams3 
- ServiceWorkers 
- WebRTC
- offline-first approach, ( pouch+couchdb, https://remotestorage.io/ )
- možno docker+nodejs
#### Predbežní sponzori sú
- [Aktiv.io](https://www.aktiv.io)
- [SaferPass](https://www.saferpass.net)
- [Progressbar](https://www.progressbar.sk)
##### Bude sponzorované jedlo + pitie

(napíšte preferenciu jedla a pitia sem do issue či už pizza, pivo, môže sa objednať cez itesco. Pod Progressbarom je taktiež [Minerva - Najlepší Burger](http://www.bratilicious.com/recenzie-clanky/najlepsi-burger-bratislava-este-lepsi) a dá sa s nimi dohodnúť )

**Ak viete o ľudoch, ktorí by sa chceli naučiť programovať, pozvite ich.**

Chcel by som zachovať gender neutrality, preto kľudne pozvite aj dievčatá, budeme dodržovať code of conduct
### S čím aktuálne potrebujem pomôcť?
- promo samotného eventu, kľudne napíšte kam to viete fwdnúť alebo kde to mám postnúť
- handsome co-organizátora
- hľadám mentorov, 5/5 node.js :)
- pritiahnuť viac dievčat/žien, aby sme držali balance
- peknú stránku nodeschool/bratislava

**Ak chcete prísť napíšte svoju približnú úroveň znalosti node.js**, napr 3/5

Matej

**Comment by maht0rz** [comment]
3.420/5!

**Comment by FilipMessa** [comment]
2/5

**Comment by olso** [comment]
3.14/5

**Comment by luckylooke** [comment]
1/5 a pravdepodobnost ucasti je 70% Diik

**Comment by yangwao** [comment]
kľudne píšte aj preferencie jedla :pizza: a pitia :beers:, v Progressbare je Club-Mate 0.5l by default, pripadne mozem ponuknut legalne nootropika.

**Comment by miluoshi** [comment]
2.5/5

**Comment by robooo** [comment]
2/5 skromne
jedlo mi je naozaj jedno ;)

**Comment by Paulooze** [comment]
2/5

**Comment by roberto68** [comment]
Mato ked ty mas 3/5 ja max 2/5. (podla mna sa podhodnocujes aspon 4/5).
btw na jedlo by sa dala vyuzit aj donaska cez ham.sk (za btc) nie? za seba some meat&salad :D
Inak co by mal robit taky handsome coorganizator? ja pomozem kludne.

**Comment by oreqizer** [comment]
3*1.337 - 1/5

**Comment by IgorOrsag** [comment]
1/5

**Comment by jsolmosi** [comment]
-1/5

**Comment by yangwao** [comment]
@roberto68 oh dik. 
Môžme aj cez ham.sk, dohodneme na mieste alebo daj link čo by si chcel zobrať. 
Ako co-org napr vyrobiť návod pre newcomers, dať spraviť vinylové nálepky NodeSchool Bratislava by sa mohli, na mieste various stuff, ľudí od navigovať do priestorov, dať vediet dalej o evente, .. a tak ďalej :)

**Comment by pejrak** [comment]
ja pridem 2/5

**Comment by jCobbSK** [comment]
1/5 :+1:

**Comment by asinex** [comment]
nodeJS 1/5

**Comment by FilipMessa** [comment]
tak nakoniec nedojdem, skoda ale musim ist do prace. Uzite si to aj zamna

**Comment by jerguslejko** [comment]
1/5

**Comment by roberto68** [comment]
git push origin master - ale mal som zamietnuty pristup? ci najprv musim spravit iny local branch a ten potom zmergujes ?

**Comment by ghost** [comment]
0/5 trochu JavaScriptu viem...to je vsetko :/

**Comment by erichstark** [comment]
0/5

**Comment by withoutidea** [comment]
0/5

**Comment by MarcelGeo** [comment]
ahoj. pridem 0/5

**Comment by SOULPWRD** [comment]
Pridem, 0/5

**Comment by KaliGIS** [comment]
Aj ja pridem, 0/5

**Comment by kubadlo** [comment]
Aj so mnou môžete počítať, 2/5.

**Comment by SamuelPecar** [comment]
2/5

**Comment by aspintm** [comment]
Node.js - 0/5. Rad sa pridem naucit nieco nove :)

**Comment by mako1131** [comment]
1/5 , rad sa zucastnim.

**Comment by kodujeme** [comment]
2/5

**Comment by jangondol** [comment]
0,66/5 - teším sa! :+1:

**Comment by newPOPE** [comment]
1/5 (len pre task runnery).

**Comment by alekseypotapov-dev** [comment]
0/5 
vidime sa!

**Comment by Cyril212** [comment]
1/5

**Comment by xrmnk** [comment]
0/5. Pridem.

**Comment by marcelmokos** [comment]
3,9 / 5 Prídem.

**Comment by zuzana** [comment]
2/5

**Comment by tomas-radic** [comment]
0/5
Jedlo: minerva by mohla byt :+1:

**Comment by kewoSK** [comment]
0/5 pridem

**Comment by jlabaj** [comment]
0.5/5

**Comment by marrej** [comment]
0/5

**Comment by ddenod** [comment]
0/5

**Comment by xcesek** [comment]
1/5

**Comment by vlapo** [comment]
2/5

**Comment by LordZombi** [comment]
2/5

**Comment by achtan** [comment]
2/5
ale dufam ze bude aj live stream s Aldo vs. McGregor https://www.youtube.com/watch?v=f_biPEdthlk :)

**Comment by Ivkaa** [comment]
0/5
jedlo je mi jedno~ teda ak sa najde aj nieco pre vegetariana :))
tesim sa! ;)

**Comment by apansky** [comment]
1/5

**Comment by bosanskamariana** [comment]
0/5

**Comment by psulek** [comment]
Asi prídem (aj nebudem v praci), nodejs  2/5

**Comment by dderevjanik** [comment]
1/5

**Comment by jurajkocan** [comment]
0/5

**Comment by mirnyyy** [comment]
mozem dojst, aj ked prd do toho vidim?

**Comment by srigi** [comment]
Dojdem a rad by som dal mini-talk/workshop na temu multithreading v Node.
4/5.

**Comment by RoverHux** [comment]
0/5, len základy JavaScript-u
nie je však 100% isté, že sa mi podarí prísť.

**Comment by Kajbo** [comment]
sorry že takto neskoro, 0/5

**Comment by marek166** [comment]
0/5

**Comment by mreguly** [comment]
0/5 veľmi rád prídem

**Comment by yangwao** [comment]
Ahoj, sumár a inštrukcie k zajtrajšku. 
**Veľka vďaka tým ktorí prídu a dopredu veľká vďaka tým, ktorí budú ochotne zdieľať svoje vedomosti so začiatočníkmi.**
Začiatočnílov bude **31** a ľudí čo uviedli aspoň nad 2/5 **21**. Čiže v pároch sa to zvládne. 
Princíp NodeSchool je pracovať najlepšie v pároch, lebo sa účastník nielen naučí viac, ale aj zabaví! :)

### Program~
- 08:30 mentors/org meet
- 10:00 opening 
- 10:30 introduction
- 11:00 setup + first chapters
- 11:00 food deadline order
- 12:00 f00d
- 13:00 TBA prednaska od @srigi (multithreading v Nodejs)
- 13:30 TBA prednaska od @newPOPE (docker intro)
- 14:00 Let's continue!
- 15:30 Coffee break (Urban bistro pravdepodobne)
- 17:00 Thanks for comming // Maybe dinner

### Akcie
- Účastníkom odporúčam si nainštalovať a rozbehať NodeJS už doma, aby sme nestrácali čas na mieste, avšak pomôžeme, 
  ak natrafíte na nejaký problém pri inštalácii.
- Účastníci s **rankom aspoň 2**, odporúčam si prejsť kurzy `javascripting` a `learnyounode`, dosť to pomôže, keď budete pripravený na otázky.
- Ľudia, ktorí chcú pomôcť orgom, by mohli prísť pred 9 :)

### [Nezabudni si objednať jedlo TU](https://github.com/nodeschool/bratislava/issues/10)

V Progressbare funguje samoobsluha, zoberiete si Club-Mate, zapíšete si čiarku na NodeSchool papier.

Keby ste ma hľadali, budem mať modré tričko s IO (palička-jupiter) :dancers: 

Na záver, každý sa pripojíte na gitter https://gitter.im/nodeschool/bratislava 
[![Join the chat at https://gitter.im/nodeschool/bratislava](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/nodeschool/bratislava?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)
môžete sa tam voľne pýtať navzájom, keby Vám niečo nešlo.

### p.s. máme nálepky :rocket:

(limited edition rev1a)

<img alt="NodeSchool Bratislava Logo" src="http://i.imgur.com/CSFFDUQ.jpg" width="200">

**Comment by psulek** [comment]
Mrzi ma to ale nebudem moct prist. Dnes nam neako nevysiel dobre release a musim cez weekend fixovat v praci :-( Snad teda v januari.

**Comment by roberto68** [comment]
dojdem nieco po 9 ale pomozem

**Comment by xrmnk** [comment]
"odporúčam si nastaviť enviroment už doma" - care to elaborate?

**Comment by luckylooke** [comment]
Nemozem prist... nabuduce sa dufam podari.. :/

**Comment by yangwao** [comment]
@xrmnk je niečo konkretne co ti neslo nastavit? Aka platforma?
