### ISSUE TITLE
NodeSchool Bratislava #4 - webgl & three.js edition

### ISSUE THREAD

**Issue by yangwao** [nodeschool/bratislava#24]
9.4. 9:30 - ~16:00

Facebook> https://www.facebook.com/events/1280166898666181/
Tickets> https://ti.to/nodeschool-bratislava/4-webgl-three-js-edition

draft desc
// Matúš Blade Koprda - Ultra rýchle zoznámenie sa s celým svetom realtime 3D grafiky a WebGL. Po tomto talku by sa človek nemal zlaknúť tých divných pojmov ako quaternion, model-view matrix, frustum, vertex buffer object, specular lighting keď bude chcieť ísť pracovať s three.js plus three.js crashcourse 

// Matej Nemček - cat from mars talk 1.9 + ipns + ako si zavesíš svôj statický web na distribuovanú sieť napr ako http://hackerdome.xyz 
- [x] :calendar: Agree on a date
- [x] :memo: Create ti.to page
- [ ] :school: :bear: Post event on nodeschool.io
- [x] :blue_book: Create facebook event
- [x] :speech_balloon:  Post to gitter channel 
- [x] :octocat: Inform on GiHub
- [ ] :cool:  Inform local FB group about upcoming event
- [ ] :house: Update homepage
- [ ] :alarm_clock: Send reminder to participants at the day of event

**Comment by yangwao** [comment]
Bladove @bladeSK poznamky k prezentacii 
=>
No, takze takto vyzera zoznam tem, ktore by som v kratkosti vysvetlil (0-2 slajdy na odrazku, na slajdoch budu vacsinou iba obrazocky:)
- co je WebGL - viac menej 1:1 OpenGL v canvase
- co je teda OpenGL?
- a three.js
  - treba povedat ako three odbremenuje od riesenia vela veci, o ktorych si dalej povieme a ze sa ich netreba zlaknut, iba vediet, ze existuju a ze ich riesi three js
  - a ze WebGL je len pre sialencov, co si chcu vsetko pisat sami a ze je natolko low level, ze je priamo (bez frameworku) takmer nepouzitelne a preto existuje three.js
- vektory, suradnice, left hand coordinate system
- primitives - trojuholniky (v CCW poradi*), ciary, body
  - trojuholnik ritou otoceny k obrazovke sa by default nevykresli
- VBOs, vseobecne princip bufferov a draw calls
  - ukazat, ze VBO sa da vykreslit ako bodky, ciary, trojuholniky, tri-strip, atd., spomenut indices?
  - spomenut stare OGL a immediate mode
  - spomenut ako ma OGL jednu state mechine, na ktoru sa kadeco binduje
- transformacie, matice, quaterniony
  - vysvetlit, ze vsetko toto staci vnimat ako cierne skrinky, ktore sa spravaju urcitym sposobom wink emoticon
  - co je frustum + culling (ako bonus mozno spomenut octrees?)
- textury, uv koordinaty
  - clamp vs wrap
  - npot, texture atlases
- GLSL, vertex a fragment shader, spomenut geometry shader
  - uniforms, varyings, attributes
- svetla, normaly
  - ambient, diffuse, specular, emissive
  - dot product, cross product vektorov
- framebuffer, ine buffery, depth test, render to texture
- hello world v three js
- kde sa ucit, spomenut znova, ze WebGL je prakticky 1:1 kopia OGL a teda daju sa v pohode studovat clanky pisane v Ccku

**Comment by drakh** [comment]
http://patriciogonzalezvivo.com/2015/thebookofshaders/

**Comment by drakh** [comment]
rychle, hladke fonty - SDF pre ThreeJS https://github.com/Jam3/three-bmfont-text

**Comment by drakh** [comment]
a pre 2D vo webGL moze byt zaujimave toto tu https://github.com/mattdesl/kami-demos

**Comment by yangwao** [comment]
Tickets> https://ti.to/nodeschool-bratislava/4-webgl-three-js-edition
