### ISSUE TITLE
Now - realtime global deployment, Next.js - A minimalistic framework for universal server-rendered React applications

### ISSUE THREAD

**Issue by marcelmokos** [nodeschool/bratislava#29]
Na workshope spolu napíšeme serverom rendrovanú React aplikáciu v minimalistickom frameworku next.js a spravíme deploy na server pomocou príkazu o troch znakoch. 
Zhrniem čo je na tomto frameworku a službe zaujímavé.

20 min. ukážka a potom priestor na otázky.
https://github.com/zeit/next.js
https://zeit.co/now

**Comment by yangwao** [comment]
Perfect! 👏  👋  👍  prípadne slajdy doplniť
