### ISSUE TITLE
Nodeschool Bratislava stickers

### ISSUE THREAD

**Issue by yangwao** [nodeschool/bratislava#3]
Ahoj, kedže by bolo fajn mať nálepky, podujme sa niekto vybaviť vinylové nálepky? Loga nodeschool sa nájdu https://github.com/nodeschool/bratislava/tree/master/assets/logo, logo Aktiv.io by som vedel dodať a Saferpass pravdepodobne tiež.
@roberto68 chce sa ti? Alebo kludne niekto dalsi, aby to nestalo len na mne.
Tip na vendorov vinylovych nalepiek mam http://www.exprestlac.sk len nemam ziadne vzorky. V Copexe sa daju spravit normalne, ale sa zosuchaju casom.
Zatial mam napad, ze dam vyrobit priblizne ~100ks nalepiek ak nebudu drahe

**Comment by roberto68** [comment]
no ok, mozem a aj ten navod napisat volajaky. Btw kolko cca tych nalepiek,
myslis take nalepky ako na notas - vyska ~8 cm ?

Dňa 2. decembra 2015, 0:24, Matej Nemček notifications@github.com
napísal(-a):

**Comment by yangwao** [comment]
nn nejake male 40x40 ~ 60x60 mm, ale dam spravit asi par kusov so starym logom a potom ked dovali nove, budu dalsie :)

**Comment by newPOPE** [comment]
@yangwao my sme tam tlacili nalepky pre rekurzia.sk a webelement.sk su v pohode. Nie su papierove ale ani nie hrube (tak akurat).

**Comment by roberto68** [comment]
tak som este prihodil universal Unix install a best practices pre setup projektu

**Comment by yangwao** [comment]
Dal som spraviť prvé nálepky, 40x46mm, 60 nálepiek / 45€, pvc plastová fólia, uvidím, uvidíte na meetupe :)

**Comment by yangwao** [comment]
expresstlac sa pokusia spraviť nové, tak keď budem v Bratislave dám vedieť či sú už lepšie (len ich asi bude treba narazať vo FabLabe) :)

**Comment by yangwao** [comment]
nejake nalepky su v Progressbare ked tak :) dalsie asi cez stickermule najlepsie, uvidime ako budu vyzerat ked pridu. Ceny su nejak 
- 10pcs/$16.21/$1.621 
- 25/$32.51/$1,3004 
- 50/$54.53/$1,0908
