### ISSUE TITLE
NodeSchool Bratislava #5 Vue.js edition

### ISSUE THREAD

**Issue by Ivkaa** [nodeschool/bratislava#30]
16.2. 18:00~21:00
Fb: https://www.facebook.com/events/1823577231190995/

We will be learning together Vue.js from tutorial, and after that, everyone will be able to create an easy static page and share it on github pages.

For those who are new to node.js, there are official nodeschool tutorials and we are ready to help you to begin or guide you through obstacles.

Attend if you want to meet up like minded  people and dive into a nodeschool workshop. There are workshops available for every skill level -- from JS beginners all the way to experienced node programmers. NodeSchool is a community driven, open source educational platform that teaches various node.js and JavaScript skills in an interactive, self-guided format.
 
NodeSchool strives to be a welcoming and safe event for all attendees. Attendees have to follow the Code of Conduct.
 
You only need to bring your laptop and laptop charger.
 
 ~talks & workshops
18.00-18.25 ~ Marcel Mokoš - prednáška o next2 beta https://github.com/zeit/next.js/  &  now https://zeit.co/now/
[10-15 min talk]
If there could be a chance to develop apps in javascript as simply as with PHP. Use server to render views and then let client to pick up and continue as single page app from one code base. React create app does not solve server rendering and many others. There is one promising option that solves mentioned above. This minimalistic framework is called next.js, it's version 2 is in beta and soon to be released.

[5-10 min talk]
Creators of next.js among other things build hosting with easy one command deploy. There is even option to deploy using apps for win, linux and macOs. Hosting can serve us as playground or production server for static files, any node server project and can run docker containers. 

18.30-21.00 ~ Vue.js workshop
Learn Vue.js step by step (https://laracasts.com/series/learn-vue-2-step-by-step/  ~ we will be doing only half of the lectures)
 
Viac info: https://github.com/nodeschool/bratislava/issues/30
RVSP https://www.meetup.com/nodeba/events/237655878/

Web http://nodeschool.io/bratislava
Nezabudni sa pripojit na gitter https://gitter.im/nodeschool/bratislava

**Comment by yangwao** [comment]
Marcel Mokoš - prednáška o next2 beta https://github.com/zeit/next.js/  &  now https://zeit.co/now/
Ivana Zemanovičová - pwa w/ vue.js 
desc http://piratepad.net/igUggXVslQ
Nezabudnut postnut event do https://www.facebook.com/groups/1565768270335828/ , https://www.facebook.com/groups/vyvojari/ https://www.facebook.com/groups/rubyslava/ https://www.facebook.com/groups/webdevgsk/ https://www.facebook.com/groups/webelement/
Meetup.com event zrobit ~~> https://www.meetup.com/nodeba/events/237655878/

**Comment by yangwao** [comment]
Good one! 👍
