### ISSUE TITLE
Sticker order for upcoming NodeSchool Bratislava from stickermule.com

### ISSUE THREAD

**Issue by yangwao** [nodeschool/bratislava#32]
#Hello, we recieved $100 in credit from Stickermule.com.
I'd like ask you to pick some great stickers from [stickermule.com](https://www.stickermule.com/uk/marketplace/) which newcomers would like to have on their coding machines :)

I'll try order them in upcoming weeks before next NodeSchool Bratislava.

Please sort them from highest wanted to lowest wanted.
Also try focus on that lower priced ones, so we can spread more stickers 💗

**Comment by yangwao** [comment]
My candidates so far 
- https://www.stickermule.com/uk/marketplace/5643-vue-dot-js-sticker
- https://www.stickermule.com/uk/marketplace/10012-gitlab-sticker
- https://www.stickermule.com/uk/marketplace/12408-node-dot-js
- https://www.stickermule.com/uk/marketplace/14722-nodejs-hex-sticker
- https://www.stickermule.com/uk/marketplace/11301-serverless-framework
- https://www.stickermule.com/uk/marketplace/10818-offline-t-rex
- https://www.stickermule.com/uk/marketplace/2375-browserify
- https://www.stickermule.com/uk/marketplace/3507-fish-shell-sticker-die-cut
- https://www.stickermule.com/uk/marketplace/1788-vim-sticker
- https://www.stickermule.com/uk/marketplace/13161-i-vim
- https://www.stickermule.com/uk/marketplace/17278-aliens-building-together
- https://www.stickermule.com/uk/marketplace/13172-rethinkdb-thinker
- https://www.stickermule.com/uk/marketplace/13988-mongodb-hex-sticker

**Comment by martinfridrich** [comment]
- https://www.stickermule.com/uk/marketplace/10376-a-space-in-the-floor
- https://www.stickermule.com/uk/marketplace/7981-4-out-of-3-people-struggle-with-math
- https://www.stickermule.com/uk/marketplace/9100-succulence
- https://www.stickermule.com/uk/marketplace/1788-vim-sticker
- https://www.stickermule.com/uk/marketplace/8994-80s-millenium-falcon
- https://www.stickermule.com/uk/marketplace/7739-tasted-the-rainbow
- https://www.stickermule.com/uk/marketplace/9663-rick-and-morty-mr-meeseeks-die-cut-premium-vinyl-sticker
- https://www.stickermule.com/uk/marketplace/9664-rick-and-morty-pet-dog-snuffles-slash-snowball-die-cut-vinyl-sticker

**Comment by jlabaj** [comment]
https://www.stickermule.com/de/marketplace/10576-angular-2
https://www.stickermule.com/marketplace/12005-webpack
https://www.stickermule.com/uk/marketplace/12408-node-dot-js
https://www.stickermule.com/marketplace/16730-rx-reactive-extensions
https://www.stickermule.com/uk/marketplace/8994-80s-millenium-falcon
https://www.stickermule.com/marketplace/12998-npm
https://www.stickermule.com/marketplace/12975-graphql
https://www.stickermule.com/marketplace/11243-docker
https://www.stickermule.com/marketplace/11935-redux
https://www.stickermule.com/marketplace/11311-reactiflux-sticker
#gottacatchemall

**Comment by Ivkaa** [comment]
https://www.stickermule.com/uk/marketplace/8986-bunch-o-cat-grapes
https://www.stickermule.com/uk/marketplace/6437-donut
https://www.stickermule.com/uk/marketplace/8984-kitty-in-a-box

**Comment by robooo** [comment]
- https://www.stickermule.com/uk/marketplace/13359-tokin-panda
- https://www.stickermule.com/uk/marketplace/9664-rick-and-morty-pet-dog-snuffles-slash-snowball-die-cut-vinyl-sticker
- https://www.stickermule.com/uk/marketplace/12408-node-dot-js
- https://www.stickermule.com/uk/marketplace/1973-reviewninja
- https://www.stickermule.com/uk/marketplace/1883-baby-groot

**Comment by yangwao** [comment]
Yay! ordered. 
> Your order is in production and will arrive by Tuesday, May 2

But I paid VAT 40€ from free order, interesting.

You can also share this link with your friends to give them £8 off their order and get £8 credit when they buy. https://www.stickermule.com/uk/unlock?ref_id=5701170701
Thanks! :)
