### ISSUE TITLE
Remove modal on web when user clicks on button "I want go"

### ISSUE THREAD

**Issue by yangwao** [nodeschool/bratislava#34]
It's been good, when we're using ti.to/typeform for 'tickets' at [nodeschool.io/bratislava](nodeschool.io/bratislava), but now I think direct link to meetup.com would be better, where folks can just RVSP.
Maybe @adammockor would know? 
Remove typeform script from here https://github.com/nodeschool/bratislava/blob/web/app/views/modules/_registration.jade could fix this?

**Comment by adammockor** [comment]
Will fix sooon!

**Comment by yangwao** [comment]
I fixed it already.
