### ISSUE TITLE
How to setup basic enviroment for nodejs

### ISSUE THREAD

**Issue by yangwao** [nodeschool/bratislava#4]
Ahoj, komu sa chce napisat do Readme.md ako setupnut basic node.js enviroment pre new-comers pre platformy
- Mac OSX
- Windows
- Linux

aby tomu rozumeli ludia, ktori nikdy nevideli terminal predtym?
Vdaka!

**Comment by yangwao** [comment]
Windows a Ubuntu uz je https://github.com/nodeschool/bratislava/pull/5
Kludne Mac OSX este :)

**Comment by roberto68** [comment]
ja som spravil aj ako setup project eslint... len to sem musim nahodit

**Comment by roberto68** [comment]
tak som to sem nahodil, universal Unix install a best practices pre setup projektu

**Comment by yangwao** [comment]
viac menej su uz basics navody, kto ich chcete potom rozviest, resp rozmenit na drobne, kludne PR :)
