### ISSUE TITLE
Nodeschool Women Edition 10. Feb. 2018

### ISSUE THREAD

**Issue by Ivkaa** [nodeschool/bratislava#41]
Are you dreaming about what is like to code? Join our workshop that is open to anyone! We would like to encourage especially women this time. 👩🏾‍💻👩🏻‍💻👩‍💻 

If you want to join, register here please 👉 https://rmbrk.typeform.com/to/DIJcCr

Please bring your 💻 (notebook) and creativity.

There will be 🍕🍕🍕 and 🍹 for all of you.

You are going to learn how to start with Javascript,
we will teach you the basics of the language, 
what you can use it for and how to use tools 
that are going to help you during coding. 

For more advanced 🦄 we will prepare some ES6 tips and/or React basics.

Link to the course: https://github.com/node-girls/beginners-javascript

Schedule for the day (approximate): 
  9:00 - Intro
  9:15 - Start of tutorials (https://github.com/node-girls/beginners-javascript/blob/master/step01.md)
  11:30 - Lunch
  12:30 - (talk) Ronald Filo: Begginers intro to blockchain ⛓- What is blockchain, why it's such a hot 
               technology and what to do if you want to start using it.  
  12:45 - (talk) Intro to dev tools
  13:00 - (talk) How to customise any page with JS 
  13:15 - Challenges (https://github.com/node-girls/beginners-javascript/blob/master/challenge01.md)
  15:45 - Final thoughts
  16:00 - Official end + Networking
  17:15 - Dinner together :)

Our sponsor is DECENT and they are looking for Node.js developers
https://decent.ch/en/careers/

Join our Nodeschool Bratislava facebook group https://www.facebook.com/groups/nodeschoolBratislava/

Join our Meetup group for further email updates https://www.meetup.com/nodejsbratislava/events/247050092/

You can find more info about what is Nodeschool at https://nodeschool.io/bratislava/

You can support Progressbar hackerspace at https://donate.progressbar.sk

You can subscribe for coworking in Progressbar https://cowork.progressbar.sk

**Comment by olso** [comment]
Test

**Comment by Ivkaa** [comment]
1.

**Comment by olso** [comment]
https://github.com/node-girls/beginners-javascript/blob/master/step01.md

**Comment by olso** [comment]
https://github.com/node-girls/node-workshop

**Comment by olso** [comment]
https://github.com/node-girls/london

**Comment by Ivkaa** [comment]
1. Set up
  - browser
  - node js
  - git

**Comment by Ivkaa** [comment]
clickbait bonuses

**Comment by Ivkaa** [comment]
we can show them this map
https://github.com/kamranahmedse/developer-roadmap

**Comment by Ivkaa** [comment]
apis that we can use:
https://medium.com/@sailorhg?format=json

https://http.cat/
https://dog.ceo/dog-api/
https://robohash.org/

**Comment by olso** [comment]
We could also think about some **icebreakers** (getting to know each other), to promote healthy interaction between attendees (not afraid to ask questions between each other)

**Comment by Ivkaa** [comment]
Let's not forget to mention that we are always looking for some ppl that will join us organise nodeschool :)

**Comment by Ivkaa** [comment]
https://javascript.info/

**Comment by yangwao** [comment]
[Project guidelines for brave ones](https://github.com/wearehive/project-guidelines)

**Comment by Ivkaa** [comment]
Schedule Draft:

9:00 - Intro (Iva)
9:15 - Start of tutorials (https://github.com/node-girls/beginners-javascript/blob/master/step01.md)
11:30 - Lunch
12:30 - Why blockchain is such a hot technology and how to handle it using Node.js (Roland Filo)
13:00 - How to customise any page with JS (?)
13:15 - Challenges (https://github.com/node-girls/beginners-javascript/blob/master/challenge01.md)
15:30 - Intro to dev tools (Olso?) // maybe this should be before the 'how to customise page' talk? 
15:45 - Final thoughts
16:00 - Official end + Networking
17:15 - Dinner together :)

Sure, some girls will probably finish tutorials sooner or later and can start challenges anytime.

**Comment by olso** [comment]
@Ivkaa i would move this schedule into repo, so anyone can add changes 🗡

**Comment by Ivkaa** [comment]
@olso Do you have any ideas about what icebreakers to try? Or maybe do some research if not? :)

**Comment by olso** [comment]
I mean it depends on the size of the group, but something basic such as, doing a round of "icebreaker" intros where they say their name, where they are from and something about their programming history or aspirations

Not everyone has to participate (in case their have some social public speaking fobia), but they should as this is the point of the icebreaker 🗡 

@Ivkaa

**Comment by Ivkaa** [comment]
@olso agree, I have been talking with @towc and also just came up with introduction. I have seen that also just introduction to the person next to you is very effective.

**Comment by Ivkaa** [comment]
http://jsforcats.com/
