### ISSUE TITLE
NodeSchool Bratislava #2 meetup 23.1.2016

### ISSUE THREAD

**Issue by yangwao** [nodeschool/bratislava#9]
Ahoj, druhé kolo, **23.1.2016 v Progressbare** zorganizujem all-day Nodeschool meetup. (~ **10am-5pm**)

**Ak viete o ľudoch, ktorí by sa chceli naučiť programovať, pozvite ich.**

**RSVP**
# [Zaregistruj sa cez tento formulár](https://yangwao.typeform.com/to/Qb8qdR)
###### Social
- [https://www.facebook.com/events/1509468479382436//](https://www.facebook.com/events/1509468479382436/)
- [http://www.meetup.com/nodeba/events/227107676/](http://www.meetup.com/nodeba/events/227107676/)

[![Join the chat at https://gitter.im/nodeschool/bratislava](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/nodeschool/bratislava?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)

If you are non-slovak speaking attendee, let me know, we speak english as well!
#### Sponzori sú
- [Aktiv.io](https://www.aktiv.io)
- [PixelFederation](http://www.PixelFederation.com)
- [Progressbar](https://www.progressbar.sk)
###### Food

~~[Pizza group order (zatiaľ žiaden sponzor)](https://github.com/nodeschool/bratislava/issues/12)~~
~~[Coffe group order (zatiaľ žiaden sponzor)](https://github.com/nodeschool/bratislava/issues/13)~~

Chcel by som zachovať gender neutrality, preto kľudne pozvite aj dievčatá, budeme dodržovať [code of conduct](https://github.com/nodeschool/bratislava/blob/master/codeofconduct.md)
### S čím aktuálne potrebujem pomôcť?
- promo samotného eventu, kľudne napíšte kam to viete fwdnúť alebo kde to mám postnúť
- handsome co-organizátora
- hľadám mentorov, 5/5 node.js :)
- pritiahnuť viac dievčat/žien, aby sme držali balance
- peknú stránku nodeschool/bratislava
## Talks wanted
- @newPOPE Docker for novice by (TBA)
- @srigi Talk o knizniciach pre SQL databazy/migracie v Node, chcete? Kratke predstavenie 2+1 kniznic, ktore sprijemnuju pracu so SQL databazami v Node. ORM pre Node. +Migracie (co to je, co na to pouzit).
- @maht0rz Music platform for shared households and open spaces.

**Ak chcete prísť [zaregistrujte sa cez tento typeform](https://yangwao.typeform.com/to/Qb8qdR)**

Matej

**Comment by adammockor** [comment]
3/5

**Comment by mariusrak** [comment]
1/5

**Comment by withoutidea** [comment]
0/5, ale dovtedy na tom ešte popracujem! :)

**Comment by erichstark** [comment]
druhy meetup. 0.5/5 ? :)

**Comment by haness** [comment]
dojdem reprezentovať ženy teda
1/5

**Comment by lukaasp** [comment]
3/5, planujem na tom popracovat :-)

**Comment by yangwao** [comment]
**UPDATE** 
šesť z Vás, ktorí ste sa zatiaľ prihlásili (samozrejme aj tí ďalší!) a chcete sa pridať do [Pizza Group order, napíšte mi to tejto issue vašu preferenciu pizze](https://github.com/nodeschool/bratislava/issues/12), 
vďaka!

**Comment by ps-aux** [comment]
0.5/5 :)

**Comment by maht0rz** [comment]
4/5

**Comment by srigi** [comment]
Talk o knizniciach pre SQL databazy/migracie v Node, chcete?
Kratke predstavenie 2+1 kniznic, ktore sprijemnuju pracu so SQL databazami v Node. ORM pre Node. +Migracie (co to je, co na to pouzit).

// edit: presnejsi popis

**Comment by mariusrak** [comment]
Chceme. Uvítal by som ArangoDB.

**Comment by yangwao** [comment]
@srigi ju, kludne, vies to rozviest? alebo na gitteri. :)

**Comment by mr-memetic** [comment]
1/5

**Comment by yangwao** [comment]
Nová, jednoduchšia forma prihlasovania https://yangwao.typeform.com/to/Qb8qdR
Tí čo ste sa uz prihlasili, môžte sa optional cez tento formulár, duplikáty vytriedim potom :)
Do buducna už cez podobný typeform radšej.

**Comment by olso** [comment]
3.14/5

**Comment by yangwao** [comment]
@olso https://yangwao.typeform.com/to/Qb8qdR

**Comment by olso** [comment]
3.15/5

**Comment by yangwao** [comment]
dalsia prezentacia bude od @maht0rz - Music platform for shared households and open spaces.

**Comment by srigi** [comment]
Ja tu prezentaciu nedavam, v sobotu mam iny program. Sorry a uzite si event.

**Comment by newPOPE** [comment]
Ahoj, ospravedlnujem sa za minuly pokec o Docker-i. Dufam, ze tentokrat to bude lepsie tak aby to bolo pre vsetkych jasne a zrozumitelne. Tymto vas chcem poziadat o vyplnenie [dotaznika](http://goo.gl/forms/bfIKzsw0Un) (aby nic dolezite neuslo a bolo spomenute). Dakujem

**Comment by yangwao** [comment]
Ahoj, súmár a inštrukcie k sobote.
Približné čísla budú **58 učastníkov**, z toho **20 účastníkov má level 5+**. 
Chcel by som poprosiť tých 20tich ľudí, aby si dali **nálepku NodeSchool na seba spredu**, aby ľudia, ktorí **potrebujú pomôcť s niečím vedeli koho osloviť**. Samozrejme môžte aj tí, ktorí si trúfate pomáhať.

### ~Program
- 8:30 orgs meetup
- 9:00 doors open
- 10:00 introduction (áno, tentokrát skúsim dlhší, lepší, pripravenejší)
- 11:30 chapters
- 12:00 f00d
- 12:30 lecture @newPOPE - Docker a veci okolo (podla vyplneneho dotaznika)
- 13:00 TBA lecture (rezervovaný slot, kto by chcel niečo povedať)
- 13:30 coffe from Urban Bistro
- 16:00 Thanks for coming, but you can stay and keep learning :)

V dotazníku ste niektorí uviedli, že by ste chceli dať prednášku na tému webpack, es6/babel, typescript, RESTful webservices using NodeJS/ExpressJS, NoSQL databases, Patterns tak sa mi ozvite na fb alebo gitteri @yangwao, niečo sa zbúcha ešte na/v sobotu! :)

V Progressbare funguje samoobsluha, zoberiete si Club-Mate, zapíšete si čiarku na NodeSchool papier pri pokladničke.
Jedlo bude objednané tentokrát na 11:30, ale aj tak počítam s meškaním.

Na záver, každý sa pripojíte na gitter https://gitter.im/nodeschool/bratislava 
[![Join the chat at https://gitter.im/nodeschool/bratislava](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/nodeschool/bratislava?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)
môžete sa tam voľne pýtať navzájom, keby Vám niečo nešlo.

### Vďaka
- Lulu, ktorá pomohla s dotazníkom 
- Fablab CVTISR, ktorý nam vylaseroval nálepky
- Že prídete :)

Na záver nejaké čísla z dotazníka 
https://yangwao.typeform.com/report/Qb8qdR/ormb
Vidíme sa :)

**Comment by newPOPE** [comment]
Prezka [docker for local development](https://docs.google.com/presentation/d/1jQhiDqgcw0I-_7p0gPipCxK_KkQt3bsoM0DmFAsACag/edit?usp=sharing)

**Comment by yangwao** [comment]
Feedback na druhy meetup semkaj https://github.com/nodeschool/bratislava/issues/14
